### ISSUE TITLE
how to use @containers feature

### ISSUE THREAD

**Issue by leonardgithub** [LeoLeBras/react-apollo-example#8]
I setup a react.js project, and add a package.json in the containers folders, but failed to use the features

// package.json
{
  "name": "@containers"
}

e.g.
Uncaught Error: Cannot find module "@containers/WriteComments"

Could you tell me which module provides the feature?

**Comment by LeoLeBras** [comment]
Hy @leonardgithub,

[This article](https://blog.callstack.io/a-cure-for-relative-requires-in-react-native-2b263cecf0f6#.6db8gbvo3) will help you to understand how it works.

**Comment by leonardgithub** [comment]
@LeoLeBras I found it is caused by the resolve->alias config in the webpack.config file for react.js, and for RN, just add a package.json with name attribute. Thanks

**Comment by LeoLeBras** [comment]
Oh sorry I thought it was a RN project.
In React.js, you can't resolve alias with package.json, you need to add resolvers in the [webpack config](https://github.com/LeoLeBras/react-apollo-example/blob/master/build/webpack.config.dev.js#L21) . If you use `flow`, you also need to specify resolvers in [flow config](https://github.com/LeoLeBras/react-apollo-example/blob/master/.flowconfig#L29-L30) .
